name: Run PetClinic API Tests

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose and build 
        run: |
          docker compose build

      - name: Run tests
        run: |
          docker compose up --abort-on-container-exit --exit-code-from api-tests

      - name: Upload Surefire XML reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: PetClinic-API-Tests/target/surefire-reports

      - name: Upload Surefire HTML report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-html-report
          path: PetClinic-API-Tests/target/reports
